package view;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.filechooser.FileNameExtensionFilter;
import javazoom.jl.decoder.JavaLayerException;
import model.Config;
import model.ListeDesSons;
import model.Son;
import tools.MusicPlayer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SR
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    private HashMap<String, JButton> buttonMap = new HashMap<String, JButton>();
    static ImageIcon imageIcon;

    private Son son;
    private ListeDesSons listeDesSons = new ListeDesSons();
    private MusicPlayer mp = new MusicPlayer();
    private boolean isPaused = false;
    private Config config;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        config = new Config();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPopupMenu = new javax.swing.JPopupMenu();
        chooseFile = new javax.swing.JMenuItem();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        soundboard = new javax.swing.JLabel();
        sr = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        pauseButton = new javax.swing.JLabel();
        stopButton = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        optionMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGrid = new javax.swing.JPanel();
        jButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        buttonPopupMenu.setBackground(new java.awt.Color(60, 62, 65));
        buttonPopupMenu.setForeground(new java.awt.Color(186, 186, 186));

        chooseFile.setBackground(new java.awt.Color(60, 62, 65));
        chooseFile.setForeground(new java.awt.Color(100, 100, 100));
        chooseFile.setText("Choose File");
        chooseFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chooseFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chooseFileMouseExited(evt);
            }
        });
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });
        buttonPopupMenu.add(chooseFile);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("title");
        setBackground(new java.awt.Color(60, 63, 64));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(60, 62, 64));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(60, 62, 64));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/cancel.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        soundboard.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        soundboard.setForeground(new java.awt.Color(186, 186, 186));
        soundboard.setText("Soundboard");

        sr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sr.setForeground(new java.awt.Color(204, 0, 153));
        sr.setText("SR");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(close)
                        .addContainerGap())
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(soundboard)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sr)
                            .addComponent(soundboard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(60, 62, 64));

        pauseButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(255, 0, 51));
        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/ic_pause_circle_outline_white_24dp_2x.png"))); // NOI18N
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pauseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pauseButtonMouseExited(evt);
            }
        });

        stopButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        stopButton.setForeground(new java.awt.Color(255, 0, 51));
        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/ic_stop_circle_outline_white_24dp_2x.png"))); // NOI18N
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stopButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopButton)
                .addGap(205, 205, 205))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(pauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(60, 62, 64));

        optionMenu.setBackground(new java.awt.Color(60, 62, 65));
        optionMenu.setForeground(new java.awt.Color(186, 186, 186));
        optionMenu.setText("Option");
        optionMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        optionMenu.setOpaque(true);
        optionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionMenuMouseExited(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(optionMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonGrid.setBackground(new java.awt.Color(60, 62, 64));
        buttonGrid.setFocusTraversalPolicyProvider(true);
        buttonGrid.setLayout(new java.awt.GridLayout(3, 3));

        jButton.setBackground(new java.awt.Color(60, 62, 65));
        jButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton.setText("button1");
        jButton.setComponentPopupMenu(buttonPopupMenu);
        jButton.setDefaultCapable(false);
        jButton.setFocusPainted(false);
        jButton.setFocusable(false);
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        buttonGrid.add(jButton);

        jButton2.setBackground(new java.awt.Color(60, 62, 65));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("button2");
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        buttonGrid.add(jButton2);

        jButton3.setBackground(new java.awt.Color(60, 62, 65));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("button3");
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        buttonGrid.add(jButton3);

        jButton4.setBackground(new java.awt.Color(60, 62, 65));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("button4");
        jButton4.setDefaultCapable(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        buttonGrid.add(jButton4);

        jButton5.setBackground(new java.awt.Color(60, 62, 65));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("button5");
        jButton5.setDefaultCapable(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        buttonGrid.add(jButton5);

        jButton6.setBackground(new java.awt.Color(60, 62, 65));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("button6");
        jButton6.setDefaultCapable(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        buttonGrid.add(jButton6);

        jButton7.setBackground(new java.awt.Color(60, 62, 65));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("button7");
        jButton7.setDefaultCapable(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        buttonGrid.add(jButton7);

        jButton8.setBackground(new java.awt.Color(60, 62, 65));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("button8");
        jButton8.setDefaultCapable(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        buttonGrid.add(jButton8);

        jButton9.setBackground(new java.awt.Color(60, 62, 65));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("button9");
        jButton9.setDefaultCapable(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        buttonGrid.add(jButton9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    int xy;
    int xx;
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void optionMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMenuMouseEntered
        // TODO add your handling code here:
        optionMenu.setBackground(new Color(30, 33, 35));
        optionMenu.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_optionMenuMouseEntered

    private void optionMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMenuMouseExited
        // TODO add your handling code here:
        optionMenu.setBackground(new Color(60, 63, 65));
        optionMenu.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
    }//GEN-LAST:event_optionMenuMouseExited

    private void pauseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseEntered
        // TODO add your handling code here:
        if (!isPaused) {
            imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_pause_circle_filled_white_24dp_2x.png"));
            pauseButton.setIcon(imageIcon);
        } else {
            imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_play_circle_filled_white_24dp_2x.png"));
            pauseButton.setIcon(imageIcon);
        }
    }//GEN-LAST:event_pauseButtonMouseEntered

    private void pauseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseExited
        // TODO add your handling code here:
        if (!isPaused) {
            imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_pause_circle_outline_white_24dp_2x.png"));
            pauseButton.setIcon(imageIcon);
        } else {
            imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_play_circle_outline_white_24dp_2x.png"));
            pauseButton.setIcon(imageIcon);
        }
    }//GEN-LAST:event_pauseButtonMouseExited

    private void stopButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseEntered
        // TODO add your handling code here:
        imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_stop_circle_filled_white_24dp_2x.png"));
        stopButton.setIcon(imageIcon);
    }//GEN-LAST:event_stopButtonMouseEntered

    private void stopButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseExited
        // TODO add your handling code here:
        imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_stop_circle_outline_white_24dp_2x.png"));
        stopButton.setIcon(imageIcon);
    }//GEN-LAST:event_stopButtonMouseExited

    private void pauseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("Pause");

        if (!isPaused) {
            try {
                mp.pause();
                isPaused = true;
                imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_play_circle_filled_white_24dp_2x.png"));
                pauseButton.setIcon(imageIcon);
            } catch (IOException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                mp.resume();
                isPaused = false;
                imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_pause_circle_filled_white_24dp_2x.png"));
                pauseButton.setIcon(imageIcon);
            } catch (JavaLayerException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_pauseButtonMouseClicked

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("Stop");
        mp.stop();
        //playerThread.stop();
    }//GEN-LAST:event_stopButtonMouseClicked

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("Play");
        JButton button = (JButton) evt.getSource();
        if (!button.getText().isEmpty()) {
            son = ListeDesSons.getSonByName(button.getText());
            try {
                son = new Son(new File("S:\\Musique\\Marshmello\\Marshmello - Hello (Marshmello Remix).mp3"));
                mp.play(son);
                imageIcon = new ImageIcon(getClass().getResource("/view/icon/ic_pause_circle_outline_white_24dp_2x.png"));
                pauseButton.setIcon(imageIcon);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JavaLayerException ex) {
                Logger.getLogger(FenetrePrincipale.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonMouseClicked

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("MP3", "mp3");
        fc.setFileFilter(fileFilter);
        fc.setAcceptAllFileFilterUsed(false);

        Action details = fc.getActionMap().get("viewTypeDetails");
        details.actionPerformed(null);
        fc.setCurrentDirectory(new File("S:\\Musique"));

        int buttonPressed = fc.showOpenDialog(FenetrePrincipale.super.getParent());

        if (buttonPressed == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            son = new Son(file);
            ListeDesSons.addSon(son);

            JMenuItem menuItem = (JMenuItem) evt.getSource();
            JPopupMenu popMenu = (JPopupMenu) menuItem.getParent();
            System.out.println(son.getName());

            for (String s : buttonMap.keySet()) {
                if (buttonMap.get(s).getComponentPopupMenu().equals(popMenu)) {
                    buttonMap.get(s).setText(son.getName());
                    break;
                }
            }

        }
        this.revalidate();
        this.pack();
        this.repaint();
    }//GEN-LAST:event_chooseFileActionPerformed

    private void chooseFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseFileMouseEntered
        // TODO add your handling code here:
        chooseFile.setForeground(Color.WHITE);
    }//GEN-LAST:event_chooseFileMouseEntered

    private void chooseFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseFileMouseExited
        // TODO add your handling code here:
        chooseFile.setForeground(new Color(100, 100, 100));
    }//GEN-LAST:event_chooseFileMouseExited

    private void optionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMenuMouseClicked
        // TODO add your handling code here:
        new FenetreConfig(this).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_optionMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonGrid;
    private javax.swing.JPopupMenu buttonPopupMenu;
    private javax.swing.JMenuItem chooseFile;
    private javax.swing.JLabel close;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel optionMenu;
    private javax.swing.JLabel pauseButton;
    private javax.swing.JLabel soundboard;
    private javax.swing.JLabel sr;
    private javax.swing.JLabel stopButton;
    // End of variables declaration//GEN-END:variables
}
